- name: Repo epel
  yum:
    name: epel-release
    state: latest
    
- name: Repo mysql8
  yum:
    name: https://dev.mysql.com/get/mysql80-community-release-el7-1.noarch.rpm
    state: present

- name: install all updates
  yum:
    name: '*'
    update_cache: yes
    state: latest
