- name: install database
  block:
  - name: Install MariaDB role and setup
    include_role:
      name: mariadb
    vars:
      mariadb_secure_installation: yes
      mariadb_databases:
        - name: '{{ mariadb_db_name }}'
          collation: utf8_general_ci
          encoding: utf8
      mariadb_users_create:
        - name: '{{ mariadb_db_user }}'
          hosts:
          - '{{ mariadb_db_host }}'
          password: "{{ mariadb_user_password }}"
          privs:
          - "{{ mariadb_db_name }}.*:ALL"
          append_privs: no
      mariadb_mysqld_config: "{{ mariadb_mysqld_config_otrs }}"
  when: otrs_skip_db == false