---

- name: instalar mariadb
  yum:
    state: present
    name: 
    - mariadb-server
    - MySQL-python

- name: copy my.cnf
  copy:
    src: ./roles/otrs/templates/my.cnf.j2
    dest: /etc/my.cnf
    mode: 0600

- name: habilitar mysql
  systemd:
    name: mariadb
    state: restarted
    enabled: yes

- name: Set root Password
  mysql_user: 
  login_password: {{ mysql_root_password }} 
  check_implicit_admin: yes 
  login_name: root 
  host: localhost 
  password: {{ mysql_root_password }} 
  state: present 
  

- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False

- name: Remove anonymous users
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User=''
  changed_when: False

- name: Disallow root login remotely
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: False

- name: Remove test database and access to it
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DROP DATABASE IF EXISTS test
    - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
  changed_when: False

- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False

#- name: criar base de dados otrs
#  mysql_db:
#    name: otrs
#    state: present
#    login_user: root
#    login_password: "{{ mysql_root_password }}"

#- name: criar usuário otrs
# mysql_user:
#   login_user: root
#   login_password: "{{ mysql_root_password }}"
#    name: "{{ user_name }}"
#    password: "{{ user_pw }}"
#    priv: '*.*:ALL,GRANT'
#    state: present
#    host: '%'

#- name: importar otrs-schema.mysql.sql
#  mysql_db:
#    login_user: root
#    login_password: "{{ mysql_root_password }}"
#    state: import
#    name: otrs
#   target: ./roles/mysql/files/otrs-schema.mysql.sql

#- name: importar - otrs-initial_insert.mysql.sql
#  mysql_db:
#    login_user: root
#    login_password: "{{ mysql_root_password }}"
#    state: import
#    name: otrs
#    target: ./roles/mysql/files/otrs-initial_insert.mysql.sql

#- name: importar otrs-schema-post.mysql.sql
#  mysql_db:
#    login_user: root
#    login_password: "{{ mysql_root_password }}"
#    state: import
#    name: otrs
#   target: ./roles/mysql/files/otrs-schema-post.mysql.sql