    - name: MariaDB | Install database
      yum:
        name: 
        - mariadb
        - mariadb-server
        - MySQL-python
        state: latest
    
    - name: MariaDB | Starting and enabled database
      service:
        name: mariadb
        state: started
        enabled: yes
    
    - name: MariaDB | Change root pass
      mysql_user: 
        name: root 
        host: "{{ item }}"
        password: "{{ mysql_root_password}}"
      with_items:
        - "{{ansible_fqdn}}"
        - 127.0.0.1
        - ::1
        - localhost

    - name: MariaDB | Publish file .my.cnf in the root home
      template:
        src: client-my-cnf.j2
        dest: /root/.my.cnf

    - name: copy my.cnf
      copy:
        src: ./roles/otrs/templates/my.cnf.j2
        dest: /etc/my.cnf
        mode: 0644
  
    - name: MariaDB | Starting and enabled database
      service:
        name: mariadb
        state: restarted
        enabled: yes

    - name: criar base de dados otrs
      mysql_db:
        name: otrs
        state: present
        login_user: root
        login_password: "{{mysql_root_password}}"
    
    - name: criar usuário otrs
      mysql_user:
        login_user: root
        login_password: "{{mysql_root_password}}"
        name: "{{user_name}}"
        password: "{{user_pw}}"
        priv: '*.*:ALL,GRANT'
        state: present
        host: '%'

    - name: importar otrs-schema.mysql.sql
      mysql_db:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        state: import
        name: otrs
        target: ./roles/mysql/files/otrs-schema.mysql.sql
    - name: importar - otrs-initial_insert.mysql.sql
      mysql_db:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        state: import
        name: otrs
        target: ./roles/mysql/files/otrs-initial_insert.mysql.sql
    - name: importar otrs-schema-post.mysql.sql
      mysql_db:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        state: import
        name: otrs
        target: ./roles/mysql/files/otrs-schema-post.mysql.sql