---
- name: download epel-release
  yum:
    name: https://dev.mysql.com/get/mysql80-community-release-el7-1.noarch.rpm
    state: present

- name: install mysql
  yum:
    state: present
    name: 
    - mysql-community-devel*
    - mysql-community-server*
    - MySQL-python
- name: copy my.cnf
  copy:
    src: ./roles/otrs/templates/my.cnf.j2
    dest: /etc/my.cnf
    mode: 0600

#- name: enable mysql
#  systemd:
#    name: mysqld
#    state: restarted
#    enabled: yes

#- name: get root password
#  shell: "grep 'A temporary password is generated for root@localhost' /var/log/messages | awk -F ' ' '{print $(NF)}'"
#  register: root_password

#- name: update expired root user password
#  command: mysql --user root --password={{ root_password.stdout }} --connect-expired-password --execute="ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql_root_password }}';"

#- name: Create a new database with name 'bobdata'
#  mysql_db:
#    name: otrs
#    state: present
#    login_user: root
#    login_password: "{{ mysql_root_password }}"

#- name: create mysql client user
#  mysql_user:
#    login_user: root
#    login_password: "{{ mysql_root_password }}"
#    name: "{{ user_name }}"
#    password: "{{ user_pw }}"
#    priv: '*.*:ALL,GRANT'
#    state: present
#    host: '%'

- name: Import file.sql similar to mysql -u <username> -p <password> < hostname.sql
  mysql_db:
    state: import
    name: otrs
    target: ./roles/otrs/templates/backup-file.sql.j2