- name: Repo EPEL
  yum:
    name: epel-release
    state: latest

- name: Repo openfunsion
  yum:
    name: http://repo.openfusion.net/centos7-x86_64/openfusion-release-0.7-1.of.el7.noarch.rpm
    state: present

- name: Repo extras.getpagespeed
  yum:
    name: https://extras.getpagespeed.com/release-el7-latest.rpm
    state: present

- name: Template a file to /etc/yum.repos.d/getpagespeed-extras.repo
  template:
    src: ./roles/otrs/templates/extras.getpagespeed.j2
    dest: /etc/yum.repos.d/getpagespeed-extras.repo
    owner: root
    group: root
    mode: '0644'

- name: install all updates
  yum:
    name: '*'
    update_cache: yes
    state: latest
