- name: Repo EPEL
  yum:
    name: epel-release
    state: latest

- name: Repo EXTRAS
  command: yum install https://extras.getpagespeed.com/release-el7-latest.rpm -y

- name: Repo OPENFUSION
  command: yum install http://repo.openfusion.net/centos7-x86_64/openfusion-release-0.7-1.of.el7.noarch.rpm -y

- name: ATUALIZAR PACOTES
  command: yum update -y