- name: Repo EPEL
  yum:
    name: epel-release
    state: latest

- name: Repo OPENFUSION
  yum:
    name: http://repo.openfusion.net/centos7-x86_64/openfusion-release-0.7-1.of.el7.noarch.rpm
    state: present

- name: upgrade de todos os pacotes
  yum:
    name: '*'
    state: latest
