- name: Repo EPEL
  yum:
    name: epel-release
    state: latest

- name: Repo openfunsion
  yum:
    name: http://repo.openfusion.net/centos7-x86_64/openfusion-release-0.7-1.of.el7.noarch.rpm
    state: present

- name: Repo extras.getpagespeed
  yum:
    name: https://extras.getpagespeed.com/release-el7-latest.rpm
    state: present

- name: install all updates
  yum:
    name: '*'
    update_cache: yes
    state: latest
