- name: Desabilistar SELINUX
  shell: sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config

- name: Populate service facts
  service_facts:

- name: Disable firewalld Services
  service:
    name: "{{item}}"
    state: stopped
    enabled: no
  loop:
   - firewalld
  when: ansible_facts.services[item] is defined
  ignore_errors: yes