- name: install otrs packages
  yum:
    state: present
    name: 
    - epel-release
    - openssl
    - mod_perl 
    - "{{ otrs_rpm_url }}"
    - "perl(Crypt::Eksblowfish::Bcrypt)" 
    - "perl(JSON::XS)" 
    - "perl(GD::Text)" 
    - "perl(Encode::HanExtra)" 
    - "perl(GD::Graph)" 
    - "perl(Mail::IMAPClient)" 
    - "perl(PDF::API2)" 
    - "perl(Text::CSV_XS)" 
    - "perl(YAML::XS)"
    - "perl(DBD::Pg)"
    - "perl(Authen::NTLM)"
    - "perl-DBD-ODBC"
    - "perl(Moo)"
    - "perl(DBD::mysql)"
    
    #notify: restart httpd