- name: Instalar Pacotes OTRS
  yum:
    state: present
    name: 
    - httpd 
    - httpd-devel
    - openssl
    - mod_perl 
    - "{{ otrs_rpm_url }}"
    - "perl(Crypt::Eksblowfish::Bcrypt)" 
    - "perl(JSON::XS)" 
    - "perl(GD::Text)" 
    - "perl(Encode::HanExtra)" 
    - "perl(GD::Graph)" 
    - "perl(Mail::IMAPClient)" 
    - "perl(PDF::API2)" 
    - "perl(Text::CSV_XS)" 
    - "perl(YAML::XS)"
    - "perl(DBD::Pg)"
    - "perl(Authen::NTLM)"
    - "perl-DBD-ODBC"
    - "perl(Moo)"
    - "perl(DBD::mysql)"
    - "perl-namespace-clean"
    - "perl-Sub-Quote"
  
- name: Habilitar Cron OTRS
  become_user: root
  shell: sudo su - otrs -c "/opt/otrs/bin/Cron.sh start"
  notify: restart crond

- name: Habilitar Apache
  service:
    name: httpd
    enabled: yes
